services:
  db-master:
    image: mysql:8
    container_name: db-master
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./../db/master:/etc/mysql/conf.d
      - db_master_data:/var/lib/mysql

  db-slave1:
    image: mysql:8
    container_name: db-slave1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./../db/slave1:/etc/mysql/conf.d
      - db_slave1_data:/var/lib/mysql
    depends_on:
      - db-master

  db-slave2:
    image: mysql:8
    container_name: db-slave2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./../db/slave2:/etc/mysql/conf.d
      - db_slave2_data:/var/lib/mysql
    depends_on:
      - db-master

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend1
    depends_on:
      - db-master
      - redis
    environment:
      DB_HOST: db-master
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: npm run dev

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend2
    depends_on:
      - db-master
      - redis
    environment:
      DB_HOST: db-master
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    command: npm run dev

  backend3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend3
    depends_on:
      - db-master
      - redis
    environment:
      DB_HOST: db-master
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3003:3000"
    command: npm run dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_BACKEND_URL: http://backend1:3000
    command: npm run dev -- --host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - frontend-dev
      - backend1
      - backend2
      - backend3
    ports:
      - "5173:80"

volumes:
  db_master_data:
  db_slave1_data:
  db_slave2_data: